### ISSUE TITLE
 The Err is nan 

### ISSUE THREAD

**Issue by raozhongyu** [fabiotosi92/SMD-Nets#7]
Hi, thanks for your great work. When I use  my own dataset which collected with the carla simulation and the baseline is 50 CM. I meet the err is nan, Can you give me some suggestion. I use the deafult setting. Thanks a lot.

**Comment by fabiotosi92** [comment]
Hi! Is it a problem that arises at the beginning of the training? 
Let's try to change the eps to a smaller value (e.g. 1e^-3) value in "lib/model/SMDHead.py".

**Comment by raozhongyu** [comment]
Yes， thanks  a lot. I also want to konw if  this code can be trained on multi-gpu.

**Comment by fabiotosi92** [comment]
We trained our models using a single GPU but the code can be adapted to use multiple GPUs.

**Comment by raozhongyu** [comment]
Thanks a lot
