### ISSUE TITLE
About the crop size

### ISSUE THREAD

**Issue by yinhanxi** [fabiotosi92/SMD-Nets#9]
When training,i set the crop size to 512×512 by default,but i have some problem with the pooling layer.
`_lib/backbone/PSMNet/submodule.py_`
`_output_branch1 = self.branch1(output_skip)_`
`_RuntimeError: Given input size: (128x32x32). Calculated output size: (128x0x0). Output size is too small_`
You set a larger size when training,right?Or there is another problem.
Thank you

**Comment by fabiotosi92** [comment]
Hi, the crop size should be set considering the _aspect_ratio_ flag. In fact, crops are computed directly on the high-resolution images. Thus, if you want images at 512x512 as input of the network during training, you should set (for example) _crop_width_=2048 and _crop_height_=2048, aspect ratio=0.25. You can find some training scripts in the **script** folder.

**Comment by yinhanxi** [comment]
> 
thankyou for sharing such a nice work^_^

**Comment by yinhanxi** [comment]
another question
Why Laplace and not Gauss
thankyou
